-- AlterTable
ALTER TABLE "History" ALTER COLUMN "current_card_balance" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "current_fare" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_cost" SET DATA TYPE DOUBLE PRECISION;
